# Artificial Neural Network

### Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [2]:
dataset = pd.read_csv("Churn_Modelling.csv")
X= dataset.iloc[:, 3:-1].values
y= dataset.iloc[:,-1].values

In [3]:
print(y)

[1 0 1 ... 1 1 0]


In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


### Encoding categorical data

Label Encoding the "Gender" column

In [5]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [6]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [31]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[1])],remainder="passthrough")
X=np.array(ct.fit_transform(X))

In [32]:
print(X)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [35]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [36]:
ann= tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [37]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

### Adding the second hidden layer

In [38]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

### Adding the output layer

In [39]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

## Part 3 - Training the ANN

### Compiling the ANN

In [40]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

### Training the ANN on the Training set

In [41]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 753us/step - loss: 0.5783 - accuracy: 0.7006
Epoch 2/100
250/250 [==============================] - 0s 764us/step - loss: 0.4552 - accuracy: 0.7969
Epoch 3/100
250/250 [==============================] - 0s 797us/step - loss: 0.4365 - accuracy: 0.8024
Epoch 4/100
250/250 [==============================] - 0s 772us/step - loss: 0.4223 - accuracy: 0.8080
Epoch 5/100
250/250 [==============================] - 0s 748us/step - loss: 0.4089 - accuracy: 0.8191
Epoch 6/100
250/250 [==============================] - 0s 739us/step - loss: 0.3950 - accuracy: 0.82920s - loss: 0.3976 - accuracy: 
Epoch 7/100
250/250 [==============================] - 0s 757us/step - loss: 0.3818 - accuracy: 0.8396
Epoch 8/100
250/250 [==============================] - 0s 755us/step - loss: 0.3707 - accuracy: 0.8464
Epoch 9/100
250/250 [==============================] - 0s 749us/step - loss: 0.3631 - accuracy: 0.8522
Epoch 10/100
250/250 [=====================

250/250 [==============================] - 0s 752us/step - loss: 0.3360 - accuracy: 0.8644
Epoch 80/100
250/250 [==============================] - 0s 744us/step - loss: 0.3365 - accuracy: 0.8627
Epoch 81/100
250/250 [==============================] - 0s 781us/step - loss: 0.3364 - accuracy: 0.8635
Epoch 82/100
250/250 [==============================] - 0s 724us/step - loss: 0.3363 - accuracy: 0.8639
Epoch 83/100
250/250 [==============================] - 0s 733us/step - loss: 0.3364 - accuracy: 0.8625
Epoch 84/100
250/250 [==============================] - 0s 725us/step - loss: 0.3363 - accuracy: 0.8630
Epoch 85/100
250/250 [==============================] - 0s 725us/step - loss: 0.3360 - accuracy: 0.8621
Epoch 86/100
250/250 [==============================] - 0s 769us/step - loss: 0.3364 - accuracy: 0.8611
Epoch 87/100
250/250 [==============================] - 0s 849us/step - loss: 0.3358 - accuracy: 0.8616
Epoch 88/100
250/250 [==============================] - 0s 736us/step - loss:

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [52]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

ValueError: X has 12 features, but StandardScaler is expecting 13 features as input.

### Predicting the Test set results

In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 0]]


### Making the Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1521   64]
 [ 207  208]]


0.8645